web:
  build: .
  container_name: "media-wizard-${ENV}"
  restart: always
  ports:
    - "${APP_PORT}:80"
  volumes:
    - ./:/code
    - ./test_data/:/test_data
  environment:
    - ENV=$ENV
    - APP_PORT=$APP_PORT
    - LOG_FILE=logs/mw.log
    - LOG_LEVEL=DEBUG
    - FLASK_DEBUG=1
